name: Build SceneView GLB Viewer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our repo
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "22"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: |
          ./gradlew \
            :app:assembleDebug \
            --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SceneView-GLB-Viewer
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
